name: $(Build.BuildId)

trigger:
 branches:
   include:
     - master/TestFixtureInitializer

variables:
- group: 'PipelineVariables'

stages:  
  - stage: Build
    jobs:
      - job: Build
        timeoutInMinutes: 480
        pool: TestAutomationExamples
        steps:
          ### Initialize Container
          - template: ./Templates/initialize-container.yml
            parameters:
              artifactversion: $(artifactVersion)
              artifactcountry: $(artifactCountry)
              forceCreateImage: $(forceCreateImage)
              licenseUrl: $(LuxBeheerBcDevLicense)

          ### install specific test apps
          - task: ALOpsAppPublish@1
            displayName: 'ALOPS - Install specific test app(s)' 
            inputs:
              usedocker: true
              installaltesttool: true
              skip_verification: true
              install_al_app_names: |
                Tests-ERM

          ### Compile and Cleanup
          - template: ./Templates/compile-publish.yml
            parameters:
              navAppVersion: '1.0.[yyyyWW].*'
              runTestSuite: true
              disabledTests: '$(Build.SourcesDirectory)/TestFixtureInitializer/Test/DisabledTests/DisabledTests-ERM.json'
              createSqlbackup: '$(createSqlBackup)'